-- SLCS / Cloudflare D1
-- Đường triển khai chuẩn: npm run db:migrate
-- Không copy riêng vài migration đầu vào D1 Console vì schema production gồm toàn bộ lịch sử trong /migrations.
-- Nếu cần điều tra database, kiểm tra schema_version và các bảng/cột đại diện trước khi can thiệp thủ công.
-- Runtime có cơ chế repair schema cũ/thiếu, nhưng migration qua Wrangler vẫn là cách triển khai chính.
-- Giới hạn khởi tạo tối đa 10.000 tài khoản (nếu được cấu hình trong schema/API) là giới hạn vận hành, không phải PBKDF2.
